apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kite 
  name: nginx-deploy
  labels:
    app: nginx-deploy-eg
    environment: testing

spec:
  replicas: 2
  selector:
    matchExpressions:
    - key: app
      operator: Exists
  strategy:
    type: RollingUpdate
    rollingUpdate: #zero downtime strategy, gradually update the pods one by one
      maxUnavailable: 1 #by default they are 25 percent 
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-deploy
        image: nginx:1.18
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: db_host
          value: "mysql"
        - name: db_port
          value: "3306"
        resources:
          requests:
            cpu: "0.2"
            memory: "10Mi"
          limits:
            cpu: "1.5"
            memory: "20Mi"
        
