apiVersion: v1 
clusters: 
  - name: dev-cluster 
    cluster: 
      server: https://dev-cluster-ip:6443 
      certificate-authority-data: #base64 encoded form of CA certificate 
  - name: prod-cluster 
    cluster: 
      server: https://prod-cluster-ip:6443 
      certificate-authority-data: #base64 encoded form of CA certificate 
users: 
  - name: vidhya 
    user: 
      client-certificate-data: #base64  encoded client certificate
      client-key-data: #base64 encoded client key 
contexts: 
  - name: vidhya@dev-cluster-context 
    context: 
      user: vidhya 
      cluster: dev-cluster 
      namespace: default 
  - name: vidhya@prod-cluster-context 
    context: 
      user: vidhya 
      cluster: prod-cluster 
      namespace: default 
current-context: vidhya@dev-cluster-context 
